version: '2'
services:
  jenkins:
    image: "${REPO}/capstone-build-slave:latest"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKER_HOST: "tcp://localhost:2375"