apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone
  region: eu-central-1

availabilityZones: ["eu-central-1a", "eu-central-1b"]

nodeGroups:
  - name: capstone-prod-workers
    labels: { role: prod-worker }
    instanceType: t2.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 4
    volumeSize: 15
    volumeType: gp2
    privateNetworking: true
    availabilityZones: ["eu-central-1a", "eu-central-1b"]
    iam:
      withAddonPolicies:
        ebs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
  - name: capstone-workers
    labels: { role: worker }
    instanceType: t2.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 15
    volumeType: gp2
    privateNetworking: true
    availabilityZones: ["eu-central-1a", "eu-central-1b"]
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
  - name: capstone-builder
    labels: { role: builder }
    instanceType: t2.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 4
    volumeSize: 15
    volumeType: gp2
    privateNetworking: true
    availabilityZones: ["eu-central-1a", "eu-central-1b"]
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
